# Generated by Django 3.0.8 on 2020-09-08 13:06

from django.db import connections, migrations, transaction
from django.db.utils import DatabaseError


@transaction.atomic
def set_query_tables(apps, schema_editor):
    CustomDatasetQuery = apps.get_model("datasets", "CustomDatasetQuery")

    for query in CustomDatasetQuery.objects.all():
        if query.tables.all():
            continue

        CustomDatasetQuery.objects.select_for_update().get(id=query.id)
        with connections[query.database.memorable_name].cursor() as cursor:
            try:
                with transaction.atomic():
                    cursor.execute(
                        f"create temporary view get_tables as (select 1 from ({query.query.strip().rstrip(';')}) sq)"
                    )
            except DatabaseError:
                continue
            cursor.execute(
                "select table_schema, table_name from information_schema.view_table_usage where view_name = 'get_tables'"
            )
            tables = cursor.fetchall()
            cursor.execute("drop view get_tables")

        for t in tables:
            query.tables.create(schema=t[0], table=t[1])


class Migration(migrations.Migration):
    dependencies = [
        ("datasets", "0052_customdatasetquerytable"),
    ]

    operations = [
        migrations.RunPython(set_query_tables),
    ]
